Fix travis error
```
PopulateIssuesJobTest#test_updates_existing_issues:
2209ArgumentError: ActiveRecord::ConnectionAdapters::PostgreSQLAdapter does not support upsert
2210    app/jobs/populate_issues_job.rb:72:in `populate_issues'
2211    app/jobs/populate_issues_job.rb:18:in `populate_multi_issues!'
2212    app/jobs/populate_issues_job.rb:13:in `perform'
2213    test/jobs/populate_issues_job_test.rb:49:in `block (3 levels) in <class:PopulateIssuesJobTest>'
2214    test/jobs/populate_issues_job_test.rb:48:in `block (2 levels) in <class:PopulateIssuesJobTest>'
2215    test/jobs/populate_issues_job_test.rb:47:in `block in <class:PopulateIssuesJobTest>'
```