Remove shoulda gems
- We are not using them in the tests.
- shoulda-context which is dependency of shoulda-matchers has a problem
  with  Ruby 2.2.0-preview1 which prevents us to upgrade to
  2.2.0-preview1.
- shoulda-context requires 'test/unit/testcase' which gives following
  error on Ruby 2.2.0-preview1 while running tests:

  $ rake test
  rake aborted!
  LoadError: cannot load such file -- test/unit/testcase