Fix slop
I don't have a `safety_assured` method (thanks Opus!) I ran migrations locally to validate they worked, so something about my flow must have triggered a change before the actual commit.

Deploying #1844 causes an error:

```
       -- safety_assured(nil)
       D, [2026-02-02T15:53:04.496858 #1236] DEBUG -- :    (1.4ms)  SELECT pg_advisory_unlock(3010662050404357335)
       rake aborted!
       StandardError: An error has occurred, all later migrations canceled: (StandardError)
       
       undefined method `safety_assured' for #<ChangeIssuesIdToBigint:0x00007f10e6d28d10 @name="ChangeIssuesIdToBigint", @version=20260202160000, @connection=nil>
       /tmp/build_92292fc4/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/migration.rb:964:in `block in method_missing'
       /tmp/build_92292fc4/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/migration.rb:935:in `block in say_with_time'
       /tmp/build_92292fc4/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/migration.rb:935:in `say_with_time'
       /tmp/build_92292fc4/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/migration.rb:954:in `method_missing'
       /tmp/build_92292fc4/db/migrate/20260202160000_change_issues_id_to_bigint.rb:14:in `up'
       /tmp/build_92292fc4/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/migration.rb:908:in `public_send'
       /tmp/build_92292fc4/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/migration.rb:908:in `exec_migration'
       /tmp/build_92292fc4/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/migration.rb:889:in `block (2 levels) in migrate'
       /tmp/build_92292fc4/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/migration.rb:888:in `block in migrate'
       /tmp/build_92292fc4/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in 
```

I think this wasn't caught in CI since it loads from schema first instead of running all migrations.