Loosen dependencies and upgrade scout_apm
Getting this error:

```
2022-10-11T20:19:07.064906+00:00 app[worker.20]: /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:73:in `rescue in run': undefined method `call' for nil:NilClass (NoMethodError)
2022-10-11T20:19:07.064910+00:00 app[worker.20]:
2022-10-11T20:19:07.064911+00:00 app[worker.20]: @callback.call(self, ex)
2022-10-11T20:19:07.064913+00:00 app[worker.20]: ^^^^^
2022-10-11T20:19:07.064916+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:67:in `run'
2022-10-11T20:19:07.064918+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/component.rb:8:in `watchdog'
2022-10-11T20:19:07.064920+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/component.rb:17:in `block in safe_thread'
2022-10-11T20:19:07.064957+00:00 app[worker.20]: /app/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/relation/finder_methods.rb:381:in `raise_record_not_found_exception!': Couldn't find RepoSubscription with 'id'=128265 (ActiveRecord::RecordNotFound)
2022-10-11T20:19:07.064960+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/relation/finder_methods.rb:475:in `find_one'
2022-10-11T20:19:07.064962+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/relation/finder_methods.rb:457:in `find_with_ids'
2022-10-11T20:19:07.064971+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/relation/finder_methods.rb:69:in `find'
2022-10-11T20:19:07.064974+00:00 app[worker.20]: from /app/app/jobs/send_single_triage_email_job.rb:5:in `perform'
2022-10-11T20:19:07.064976+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/execution.rb:59:in `block in _perform_job'
2022-10-11T20:19:07.064985+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
2022-10-11T20:19:07.064988+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sentry-raven-2.13.0/lib/raven/integrations/rails/active_job.rb:13:in `block (2 levels) in included'
2022-10-11T20:19:07.064990+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `instance_exec'
2022-10-11T20:19:07.064992+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
2022-10-11T20:19:07.065000+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/i18n-1.12.0/lib/i18n.rb:322:in `with_locale'
2022-10-11T20:19:07.065002+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
2022-10-11T20:19:07.065004+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `instance_exec'
2022-10-11T20:19:07.065007+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
2022-10-11T20:19:07.065015+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
2022-10-11T20:19:07.065017+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
2022-10-11T20:19:07.065027+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `instance_exec'
2022-10-11T20:19:07.065029+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
2022-10-11T20:19:07.065038+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:138:in `run_callbacks'
2022-10-11T20:19:07.065040+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/execution.rb:58:in `_perform_job'
2022-10-11T20:19:07.065042+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/instrumentation.rb:20:in `_perform_job'
2022-10-11T20:19:07.065044+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/execution.rb:46:in `perform_now'
2022-10-11T20:19:07.065053+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/instrumentation.rb:14:in `block in perform_now'
2022-10-11T20:19:07.065055+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/instrumentation.rb:25:in `block in instrument'
2022-10-11T20:19:07.065057+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/notifications.rb:206:in `block in instrument'
2022-10-11T20:19:07.065059+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
2022-10-11T20:19:07.065068+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/notifications.rb:206:in `instrument'
2022-10-11T20:19:07.065070+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/instrumentation.rb:35:in `instrument'
2022-10-11T20:19:07.065073+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/instrumentation.rb:14:in `perform_now'
2022-10-11T20:19:07.065075+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/logging.rb:18:in `block in perform_now'
2022-10-11T20:19:07.065083+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/tagged_logging.rb:99:in `block in tagged'
2022-10-11T20:19:07.065085+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/tagged_logging.rb:37:in `tagged'
2022-10-11T20:19:07.065087+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/tagged_logging.rb:99:in `tagged'
2022-10-11T20:19:07.065089+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/logging.rb:25:in `tag_logger'
2022-10-11T20:19:07.065098+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/logging.rb:18:in `perform_now'
2022-10-11T20:19:07.065101+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/execution.rb:24:in `block in execute'
2022-10-11T20:19:07.065110+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
2022-10-11T20:19:07.065112+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/railtie.rb:54:in `block (4 levels) in <class:Railtie>'
2022-10-11T20:19:07.065114+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/execution_wrapper.rb:92:in `wrap'
2022-10-11T20:19:07.065122+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/reloader.rb:72:in `block in wrap'
2022-10-11T20:19:07.065124+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/execution_wrapper.rb:88:in `wrap'
2022-10-11T20:19:07.065133+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/reloader.rb:71:in `wrap'
2022-10-11T20:19:07.065137+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/railtie.rb:53:in `block (3 levels) in <class:Railtie>'
2022-10-11T20:19:07.065139+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `instance_exec'
2022-10-11T20:19:07.065141+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
2022-10-11T20:19:07.065143+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:138:in `run_callbacks'
2022-10-11T20:19:07.065151+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/execution.rb:22:in `execute'
2022-10-11T20:19:07.065153+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.4/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
2022-10-11T20:19:07.065155+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:202:in `execute_job'
2022-10-11T20:19:07.065164+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:170:in `block (2 levels) in process'
2022-10-11T20:19:07.065166+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/middleware/chain.rb:177:in `block in invoke'
2022-10-11T20:19:07.065167+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/scout_apm-4.1.2/lib/scout_apm/background_job_integrations/sidekiq.rb:68:in `call'
2022-10-11T20:19:07.065176+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/middleware/chain.rb:179:in `block in invoke'
2022-10-11T20:19:07.065178+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sentry-raven-2.13.0/lib/raven/integrations/sidekiq.rb:9:in `call'
2022-10-11T20:19:07.065187+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/middleware/chain.rb:179:in `block in invoke'
2022-10-11T20:19:07.065189+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/skylight-5.3.3/lib/skylight/sidekiq.rb:33:in `block in call'
2022-10-11T20:19:07.065191+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/skylight-5.3.3/lib/skylight.rb:150:in `block in trace'
2022-10-11T20:19:07.065199+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/skylight-5.3.3/lib/skylight/instrumenter.rb:224:in `trace'
2022-10-11T20:19:07.065201+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/skylight-5.3.3/lib/skylight.rb:149:in `trace'
2022-10-11T20:19:07.065203+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/skylight-5.3.3/lib/skylight/sidekiq.rb:32:in `call'
2022-10-11T20:19:07.065211+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/middleware/chain.rb:179:in `block in invoke'
2022-10-11T20:19:07.065213+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/middleware/chain.rb:182:in `invoke'
2022-10-11T20:19:07.065215+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:169:in `block in process'
2022-10-11T20:19:07.065223+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
2022-10-11T20:19:07.065225+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/job_retry.rb:113:in `local'
2022-10-11T20:19:07.065227+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
2022-10-11T20:19:07.065235+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/rails.rb:14:in `block in call'
2022-10-11T20:19:07.065237+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/execution_wrapper.rb:92:in `wrap'
2022-10-11T20:19:07.065239+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/reloader.rb:72:in `block in wrap'
2022-10-11T20:19:07.065248+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/execution_wrapper.rb:92:in `wrap'
2022-10-11T20:19:07.065250+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/reloader.rb:71:in `wrap'
2022-10-11T20:19:07.065259+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/rails.rb:13:in `call'
2022-10-11T20:19:07.065261+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
2022-10-11T20:19:07.065269+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:263:in `stats'
2022-10-11T20:19:07.065271+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
2022-10-11T20:19:07.065273+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/job_logger.rb:13:in `call'
2022-10-11T20:19:07.065282+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
2022-10-11T20:19:07.065283+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/job_retry.rb:80:in `global'
2022-10-11T20:19:07.065286+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:124:in `block in dispatch'
2022-10-11T20:19:07.065294+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/job_logger.rb:39:in `prepare'
2022-10-11T20:19:07.065296+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:123:in `dispatch'
2022-10-11T20:19:07.065298+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:168:in `process'
2022-10-11T20:19:07.065306+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:78:in `process_one'
2022-10-11T20:19:07.065308+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/processor.rb:68:in `run'
2022-10-11T20:19:07.065310+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/component.rb:8:in `watchdog'
2022-10-11T20:19:07.065318+00:00 app[worker.20]: from /app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.7/lib/sidekiq/component.rb:17:in `block in safe_thread'
```

Possibly caused by scout: https://github.com/scoutapp/scout_apm_ruby/issues/449